version: '3.8'

services:
  # Main Cybersecurity Application
  cybersec-app:
    image: himanshutoshniwal7570/cybersec-platform:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cybersec-platform
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    volumes:
      - ./logs:/app/logs
      - ./reports:/app/reports
      - ./scans:/app/scans
    restart: unless-stopped
    networks:
      - cybersec-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: cybersec-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - cybersec-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local

networks:
  cybersec-network:
    driver: bridge